// Auto-generated by gasnuki
// Do NOT edit this file manually.

export type ServerScripts = {
  /**
   * ダッシュボード用データ取得
   */
  getFlows(): string;

  /**
   * 詳細データ取得
   */
  getFlowData(flowId: string, versionId: string): string;

  saveDraft(payload: {
    flowId: string;
    title: string;
    graphData: object;
  }): string;

  submitFlow(payload: {
    flowId: string;
    versionId: string;
    comment: string;
  }): string;

  approveFlow(payload: {
    flowId: string;
    versionId: string;
    comment: string;
    graphData?: object;
  }): string;

  rejectFlow(payload: {
    flowId: string;
    versionId: string;
    comment: string;
  }): string;

  /**
   * フォルダ権限取得
   */
  getFolderPermissions(folderId: string): string;

  /**
   * 権限追加
   */
  addFolderPermission(payload: {
    folderId: string;
    email: string;
    role: string;
  }): string;

  /**
   * 権限更新
   */
  updateFolderPermission(payload: {
    permissionId: string;
    role: string;
  }): string;

  /**
   * 権限削除
   */
  removeFolderPermission(payload: { permissionId: string }): string;

  /**
   * 詳細検索
   */
  searchFlows(payload: AdvancedSearchQuery): string;

  generateUUID(): string;

  getDateString(targetDate: Date): string;

  generateDraftVersionId(email: string): string;

  generateReleaseVersionId(existingVersions: string[]): string;
}

// Auto-generated Types for GoogleAppsScript in client-side code

export type RemoveReturnType<T> = {
  [P in keyof T]: T[P] extends (...args: infer A) => any
    ? (...args: A) => void
    : T[P];
};

type _AppsScriptRun = RemoveReturnType<ServerScripts> & {
  [key: string]: (...args: any[]) => any;
  withSuccessHandler: <T = string | number | boolean | undefined, U = any>(
    callback: (returnValues: T, userObject?: U) => void,
  ) => _AppsScriptRun;
  withFailureHandler: <U = any>(
    callback: (error: Error, userObject?: U) => void,
  ) => _AppsScriptRun;
  withUserObject: <U = any>(userObject: U) => _AppsScriptRun;
};

type _AppsScriptHistoryFunction = (
  stateObject: object,
  params: object,
  hash: string,
) => void;

interface _WebAppLocationType {
  hash: string;
  parameter: Record<string, string>;
  parameters: Record<string, string[]>;
}

export declare interface GoogleClientSideApi {
  script: {
    run: _AppsScriptRun;
    url: {
      getLocation: (callback: (location: _WebAppLocationType) => void) => void;
    };
    history: {
      push: _AppsScriptHistoryFunction;
      replace: _AppsScriptHistoryFunction;
      setChangeHandler: (
        callback: (e: { state: object; location: _WebAppLocationType }) => void,
      ) => void;
    };
  };
}

declare global {
  const google: GoogleClientSideApi;
}
