// Auto-generated by gasnuki
// Do NOT edit this file manually.

import type { Role } from '../flow';

export interface PermissionRow {
  permission_id: string;
  folder_id: string;
  subject_email: string; // User Email or Group ID
  role: Role;
}

export interface FlowRow {
  flow_id: string;
  folder_id: string;
  // ...others
}

export interface UserRow {
  email: string;
  groups: string; // カンマ区切り文字列 "group-a,group-b" を想定
}

export type ServerScripts = {
  /**
   * ダッシュボード用: フロー一覧取得
   * - 権限: ログインユーザーに関連するフォルダのフローのみ
   */
  getFlows(): string;

  /**
   * フォルダ一覧取得
   */
  getFolders(): string;

  /**
   * フォルダ権限一覧取得
   */
  getFolderPermissions(folderId: string): string;

  /**
   * フォルダ権限追加
   */
  addFolderPermission(folderId: string, email: string, role: string): string;

  /**
   * フォルダ権限削除
   */
  removeFolderPermission(permissionId: string): string;

  /**
   * フォルダ権限更新
   */
  updateFolderPermission(permissionId: string, role: string): string;

  /**
   * フローのバージョン履歴（サマリ）取得
   */
  getFlowVersions(flowId: string): string;

  /**
   * サーバーサイド横断検索
   */
  searchFlows(query: string): string;

  /**
   * 編集画面・閲覧画面データ取得
   * - 必須: flowId, versionId
   */
  getFlowData(flowId: string, versionId: string): string;

  /**
   * 下書き保存
   * - 権限: EDITOR以上
   */
  saveDraft(payload: {
    flowId: string;
    title: string;
    graphData: object;
  }): string;

  /**
   * 承認申請
   * - 権限: EDITOR以上
   */
  submitFlow(payload: {
    flowId: string;
    versionId: string;
    comment: string;
  }): string;

  /**
   * 承認実行 (Approve)
   * - 権限: APPROVER以上
   */
  approveFlow(payload: {
    flowId: string;
    versionId: string;
    comment: string;
    graphData?: object;
  }): string;

  /**
   * 否認実行 (Reject)
   * - 権限: APPROVER以上
   */
  rejectFlow(payload: {
    flowId: string;
    versionId: string;
    comment: string;
  }): string;

  generateUUID(): string;

  getDateString(targetDate: Date): string;

  generateDraftVersionId(email: string): string;

  generateReleaseVersionId(existingVersions: string[]): string;
};

// Auto-generated Types for GoogleAppsScript in client-side code

export type RemoveReturnType<T> = {
  [P in keyof T]: T[P] extends (...args: infer A) => any
    ? (...args: A) => void
    : T[P];
};

type _AppsScriptRun = RemoveReturnType<ServerScripts> & {
  [key: string]: (...args: any[]) => any;
  withSuccessHandler: <T = string | number | boolean | undefined, U = any>(
    callback: (returnValues: T, userObject?: U) => void,
  ) => _AppsScriptRun;
  withFailureHandler: <U = any>(
    callback: (error: Error, userObject?: U) => void,
  ) => _AppsScriptRun;
  withUserObject: <U = any>(userObject: U) => _AppsScriptRun;
};

type _AppsScriptHistoryFunction = (
  stateObject: object,
  params: object,
  hash: string,
) => void;

interface _WebAppLocationType {
  hash: string;
  parameter: Record<string, string>;
  parameters: Record<string, string[]>;
}

export declare interface GoogleClientSideApi {
  script: {
    run: _AppsScriptRun;
    url: {
      getLocation: (callback: (location: _WebAppLocationType) => void) => void;
    };
    history: {
      push: _AppsScriptHistoryFunction;
      replace: _AppsScriptHistoryFunction;
      setChangeHandler: (
        callback: (e: { state: object; location: _WebAppLocationType }) => void,
      ) => void;
    };
  };
}

declare global {
  const google: GoogleClientSideApi;
}
