// Auto-generated by gasnuki
// Do NOT edit this file manually.

import type { JsonString } from '@ciderjs/gasnuki/json';
import type {
  FlowData,
  FlowGraphData,
  FlowMeta,
  FlowVersionDetail,
  Folder,
  Role,
} from '../flow';

export type FlowDataWithRole = FlowData & { userRole: Role | null };

export interface PermissionRow {
  permissionId: string;
  folderId: string;
  subjectEmail: string; // User Email or Group ID
  role: Role;
}

export interface FlowRow {
  flowId: string;
  folderId: string;
  // ...others
}

export interface UserRow {
  email: string;
  groups: string; // カンマ区切り文字列 "group-a,group-b" を想定
}

export type LogAction =
  | 'APPROVE_FLOW'
  | 'REJECT_FLOW'
  | 'SUBMIT_FLOW'
  | 'ADD_PERMISSION'
  | 'REMOVE_PERMISSION'
  | 'UPDATE_PERMISSION';

export interface FlowRow {
  flowId: string;
  folderId: string;
  title: string;
  currentStatus: string;
  activeVersionId: string;
  updatedAt: string | Date;
}

export interface FlowVersionRow {
  versionId: string;
  flowId: string;
  versionNum: number;
  status: string;
  jsonData: string;
  // Extra columns for large data support
  jsonData2?: string;
  jsonData3?: string;
  jsonData4?: string;
  jsonData5?: string;
  createdBy: string;
  createdAt: string | Date;
  updatedAt?: string | Date;
  comment: string;
}

export type ServerScripts = {
  /**
   * ダッシュボード用: フロー一覧取得
   * - 権限: ログインユーザーに関連するフォルダのフローのみ
   */
  getFlows(): JsonString<FlowMeta[]>;

  /**
   * フォルダ一覧取得
   */
  getFolders(): JsonString<Folder[]>;

  /**
   * フォルダ権限取得
   */
  getFolderPermissions(
    folderId: string,
  ): JsonString<(PermissionRow & { avatarUrl?: string })[]>;

  /**
   * フォルダ権限追加
   */
  addFolderPermission(
    folderId: string,
    email: string,
    role: Role,
  ): JsonString<PermissionRow>;

  /**
   * フォルダ権限削除
   */
  removeFolderPermission(
    permissionId: string,
  ): JsonString<{ success: boolean; permissionId: string }>;

  /**
   * フォルダ権限更新
   */
  updateFolderPermission(
    permissionId: string,
    role: Role,
  ): JsonString<PermissionRow>;

  /**
   * フローのバージョン一覧取得
   */
  getFlowVersions(flowId: string): JsonString<FlowVersionDetail[]>;

  /**
   * フロー検索
   */
  searchFlows(query: string): JsonString<FlowMeta[]>;

  /**
   * 編集画面・閲覧画面データ取得
   * - 必須: flowId, versionId
   */
  getFlowData(flowId: string, versionId: string): JsonString<FlowDataWithRole>;

  /**
   * 下書き保存
   * - 権限: EDITOR以上
   */
  saveDraft(payload: {
    flowId: string;
    title: string;
    graphData: FlowGraphData;
  }): JsonString<{ versionId: string }>;

  /**
   * 承認申請
   * - 権限: EDITOR以上
   */
  submitFlow(payload: {
    flowId: string;
    versionId: string;
    comment: string;
  }): JsonString<{ status: string }>;

  /**
   * 承認実行 (Approve)
   * - 権限: APPROVER以上
   */
  approveFlow(payload: {
    flowId: string;
    versionId: string;
    comment: string;
    graphData?: FlowGraphData;
  }): JsonString<{ status: string; versionId: string }>;

  /**
   * 否認実行 (Reject)
   * - 権限: APPROVER以上
   */
  rejectFlow(payload: {
    flowId: string;
    versionId: string;
    comment: string;
  }): JsonString<{ status: string }>;

  /**
   * 編集開始通知 (Heartbeat)
   * - 戻り値: { success: boolean; lockedBy?: string }
   */
  startEditing(
    flowId: string,
  ): JsonString<{ success: boolean; lockedBy?: string }>;

  toFlowMeta(row: FlowRow): FlowMeta;

  toFlowVersionDetail(row: FlowVersionRow): FlowVersionDetail;

  splitJsonData(jsonString: string): Record<string, string>;

  joinJsonChunks(row: FlowVersionRow): string;

  generateUUID(): string;

  getDateString(targetDate: Date): string;

  generateDraftVersionId(email: string): string;

  generateReleaseVersionId(existingVersions: string[]): string;
};

// Auto-generated Types for GoogleAppsScript in client-side code

export type RemoveReturnType<T> = {
  [P in keyof T]: T[P] extends (...args: infer A) => any
    ? (...args: A) => void
    : T[P];
};

type _AppsScriptRun = RemoveReturnType<ServerScripts> & {
  [key: string]: (...args: any[]) => any;
  withSuccessHandler: <T = string | number | boolean | undefined, U = any>(
    callback: (returnValues: T, userObject?: U) => void,
  ) => _AppsScriptRun;
  withFailureHandler: <U = any>(
    callback: (error: Error, userObject?: U) => void,
  ) => _AppsScriptRun;
  withUserObject: <U = any>(userObject: U) => _AppsScriptRun;
};

type _AppsScriptHistoryFunction = (
  stateObject: object,
  params: object,
  hash: string,
) => void;

interface _WebAppLocationType {
  hash: string;
  parameter: Record<string, string>;
  parameters: Record<string, string[]>;
}

export declare interface GoogleClientSideApi {
  script: {
    run: _AppsScriptRun;
    url: {
      getLocation: (callback: (location: _WebAppLocationType) => void) => void;
    };
    history: {
      push: _AppsScriptHistoryFunction;
      replace: _AppsScriptHistoryFunction;
      setChangeHandler: (
        callback: (e: { state: object; location: _WebAppLocationType }) => void,
      ) => void;
    };
  };
}

declare global {
  const google: GoogleClientSideApi;
}
